### ISSUE TITLE
Can't merge LyCORIS with algo=full

### ISSUE THREAD

**Issue by vvern999** [KohakuBlueleaf/LyCORIS#113]
I have LyCORIS trained with "algo=full" "preset=attn-mlp" "train_norm=False", using version 1.9.0. When trying to merge it with tools\merge.py i get the following error:
```
UNet2DConditionModel: 64, 8, 768, False, False
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
Converting Dtype and Device: 100%|████████████████████████████████████████████████████████████████████| 432/432 [00:02<00:00, 199.49it/s]
Merging lora_te: 100%|████████████████████████████████████████████████████████████████████████████████| 152/152 [00:00<00:00, 209.19it/s]
Merging lora_unet:   0%|▏                                                                                        | 1/633 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "G:\sd-scripts\LyCORIS\tools\merge.py", line 86, in <module>
    main()
  File "G:\sd-scripts\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\sd-scripts\LyCORIS\tools\merge.py", line 70, in main
    merge(
  File "G:\sd-scripts\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\sd-scripts\venv\lib\site-packages\lycoris\utils\__init__.py", line 528, in merge
    merge_state_dict(
  File "G:\sd-scripts\venv\lib\site-packages\lycoris\utils\__init__.py", line 505, in merge_state_dict
    result, result_b = rebuild_weight(*get_module(
  File "G:\sd-scripts\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\sd-scripts\venv\lib\site-packages\lycoris\utils\__init__.py", line 447, in rebuild_weight
    raise NotImplementedError
NotImplementedError

```
If i replace  `raise NotImplementedError` at line 447 with `pass ` it merges (at least changes to text encoder are applied)

**Comment by vvern999** [comment]
Also got this while training. kohya 0.6.6, lycoris-lora 1.9.0:
```
Traceback (most recent call last):
  File "G:\sd-scripts\train_network.py", line 1006, in <module>
    trainer.train(args)
  File "G:\sd-scripts\train_network.py", line 824, in train
    keys_scaled, mean_norm, maximum_norm = network.apply_max_norm_regularization(
  File "G:\sd-scripts\venv\lib\site-packages\lycoris\kohya\__init__.py", line 605, in apply_max_norm_regularization
    scaled, norm = lora.apply_max_norm(max_norm_value, device)
  File "G:\sd-scripts\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\sd-scripts\venv\lib\site-packages\lycoris\modules\full.py", line 87, in apply_max_norm
    self.diff_b *= ratio
TypeError: unsupported operand type(s) for *=: 'NoneType' and 'Tensor'

```

**Comment by KohakuBlueleaf** [comment]
Yes it is not supported at this time, will impl it in the future 
(maybe this week

**Comment by lulu-xiao** [comment]
Any updates regarding this?

> Yes it is not supported at this time, will impl it in the future (maybe this week

**Comment by KohakuBlueleaf** [comment]
> Any updates regarding this?
> 
> > Yes it is not supported at this time, will impl it in the future (maybe this week

Sry I'm in midterm recently
Planned update will be next weekends.
You can notice me again in next weekend.

**Comment by KohakuBlueleaf** [comment]
Fixed in latest dev, plz check.

**Comment by KohakuBlueleaf** [comment]
extract script is working normally (reported by @cyber-meow )
closed
