### ISSUE TITLE
ZeroDivisionError when training GLora with scale_weight_norm != 0

### ISSUE THREAD

**Issue by v0xie** [KohakuBlueleaf/LyCORIS#114]
Training with kohya fails on the first step if arguiment `--scale_weight_norms 5` is specified. Training without specifying scale_weight_norms argument, or specifying a different algo such as "algo=loha" successfully trains the network.

```
Traceback (most recent call last):
  File "F:\stablediffusion\kohya_ss\sdxl_train_network.py", line 183, in <module>
    trainer.train(args)
  File "F:\stablediffusion\kohya_ss\train_network.py", line 827, in train
    keys_scaled, mean_norm, maximum_norm = network.apply_max_norm_regularization(
  File "F:\stablediffusion\kohya_ss\venv\lib\site-packages\lycoris\kohya\__init__.py", line 615, in apply_max_norm_regularization
    return scaled, sum(norms)/len(norms), max(norms)
ZeroDivisionError: division by zero
```

**Comment by KohakuBlueleaf** [comment]
Thx for report

**Comment by KohakuBlueleaf** [comment]
This issue should be solved by previous version.
Plz check you have latest version.
