### ISSUE TITLE
Error while training full lycoris with --scale_weight_norms

### ISSUE THREAD

**Issue by vvern999** [KohakuBlueleaf/LyCORIS#119]
It crashes when it tries to scale.
Settings: --network_module lycoris.kohya --network_args "algo=full" "preset=full-lin" "train_norm=True" --scale_weight_norms=1
```
Traceback (most recent call last):
  File "G:\sd-scripts\train_network.py", line 1013, in <module>
    trainer.train(args)
  File "G:\sd-scripts\train_network.py", line 836, in train
    keys_scaled, mean_norm, maximum_norm = network.apply_max_norm_regularization(
  File "G:\sd-scripts\venv\lib\site-packages\lycoris\kohya\__init__.py", line 605, in apply_max_norm_regularization
    scaled, norm = lora.apply_max_norm(max_norm_value, device)
  File "G:\sd-scripts\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\sd-scripts\venv\lib\site-packages\lycoris\modules\full.py", line 87, in apply_max_norm
    self.diff_b *= ratio
TypeError: unsupported operand type(s) for *=: 'NoneType' and 'Tensor'
```

**Comment by KohakuBlueleaf** [comment]
This should be fixed in latest dev
plz check it

**Comment by KohakuBlueleaf** [comment]
corrections: full module is not support scaled_weight_norm in latest dev (switch to simpler implementation)
so we don't have any issue relate about it now.
