### ISSUE TITLE
I am using this process for sdxl dreambooth model lycoris model extracting and i am getting this error so how can i fix this error

### ISSUE THREAD

**Issue by nanaj96** [KohakuBlueleaf/LyCORIS#125]
this is my lycoris extracting model settiing
python extract_locon.py --safetensors --device=cuda --mode="fixed" --linear_dim=32 --conv_dim=32 /content/drive/MyDrive/ComfyUI/models/checkpoints/sd_xl_base_1.0.safetensors /content/drive/MyDrive/serena_sdxl/model/serena_sitter_dream_sdxl-000006.safetensors /content/drive/MyDrive/Lora/serena_sitter_lycoris.safetensors

and this i got this error

Traceback (most recent call last):
  File "/content/LyCORIS/tools/extract_locon.py", line 88, in <module>
    from lycoris.utils import extract_diff
ModuleNotFoundError: No module named 'lycoris.utils'

**Comment by KohakuBlueleaf** [comment]
My fault
Will fix it

**Comment by nanaj96** [comment]
ok please, thanks

**Comment by KohakuBlueleaf** [comment]
@nanaj96 I have tested again
it looks like you don't have cloned whole repository?

**Comment by nanaj96** [comment]
> @nanaj96 I have tested again it looks like you don't have cloned whole repository?

yeah i have used the dev repository should I use the main branch? but if i use main branch is this work for sdxl 1.0 version

**Comment by KohakuBlueleaf** [comment]
> > @nanaj96 I have tested again it looks like you don't have cloned whole repository?
> 
> yeah i have used the dev repository should I use the main branch? but if i use main branch is this work for sdxl 1.0 version

Aha I know what you met


Don't run `merge.py` in tool directory
Run 'tools/merge.py' in root directory of LyCORIS

**Comment by nanaj96** [comment]
> > > @nanaj96 I have tested again it looks like you don't have cloned whole repository?
> > 
> > 
> > yeah i have used the dev repository should I use the main branch? but if i use main branch is this work for sdxl 1.0 version
> 
> Aha I know what you met
> 
> Don't run `merge.py` in tool directory Run 'tools/merge.py' in root directory of LyCORIS

but i want to do extract lycoris not merge

**Comment by KohakuBlueleaf** [comment]
That is same
Just call tools in root directory

**Comment by KohakuBlueleaf** [comment]
LyCORIS/> python3 tools/extract_locon.py

**Comment by nanaj96** [comment]
> LyCORIS/> python3 tools/extract_locon.py

now i getting this error with sdxl 

       size mismatch for down_blocks.1.attentions.0.proj_in.weight: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([640, 640, 1, 1]).
        size mismatch for down_blocks.1.attentions.0.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([640, 2048]) from checkpoint, the shape in current model is torch.Size([640, 768]).
        size mismatch for down_blocks.1.attentions.0.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([640, 2048]) from checkpoint, the
am with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1280, 1, 1]).
        size mismatch for up_blocks.0.resnets.2.norm1.weight: copying a param with shape torch.Size([1920]) from checkpoint, the shape in current model is torch.Size([2560]).
        size mismatch for up_blocks.0.resnets.2.norm1.bias: copying a param with shape torch.Size([1920]) from checkpoint, the shape in current model is torch.Size([2560]).
        size mismatch for up_blocks.0.resnets.2.conv1.weight: copying a param with shape torch.Size([1280, 1920, 3, 3]) from checkpoint, the shape in current model is torch.Size([1280, 2560, 3, 3]).
        size mismatch for up_blocks.0.resnets.2.conv_shortcut.weight: copying a param with shape torch.Size([1280, 1920, 1, 1]) from checkpoint, the shape in current model is torch.Size([1280, 2560, 1, 1]).
        size mismatch for up_blocks.1.attentions.0.norm.weight: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
        size mismatch for up_blocks.1.attentions.0.norm.bias: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
        size mismatch for up_blocks.1.attentions.0.proj_in.weight: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([1280, 1280, 1, 1]).
        size mismatch for up_blocks.1.attentions.0.proj_in.bias: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
        s
weight: copying a param with shape torch.Size([640, 2048]) from checkpoint, the shape in current model is torch.Size([1280, 768]).
        size mismatch for up_blocks.1.attentions.0.transformer_blocks.0.attn2.to_out.0.weight: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([1280, 1280]).
        size mismatch for up_blocks.1.attentions.0.transformer_blocks.0.attn2.to_out.0.bias: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
        size mismatch for up_blocks.1.attentions.0.transformer_blocks.0.norm1.weight: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
        size mismatch for up_blocks.1.attentions.0.transformer_blocks.0.norm1.bias: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
        size mismatch for up_blocks.1.attentions.0.transformer_blocks.0.norm2.weight: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
        size mismatch for up_blocks.1.attentions.0.transformer_blocks.0.norm2.bias: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
        size mismatch for up_blocks.1.attentions.0.transformer_blocks.0.norm3.weight: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
        size mismatch for up_blocks.1.attentions.0.transformer_blocks.0.norm3.bias: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
        size mismatch for up_blocks.1.attentions.0.proj_out.weight: copying
oj.bias: copying a param with shape torch.Size([5120]) from checkpoint, the shape in current model is torch.Size([10240]).
        size mismatch for up_blocks.1.attentions.1.transformer_blocks.0.ff.net.2.weight: copying a param with shape torch.Size([640, 2560]) from checkpoint, the shape in current model is torch.Size([1280, 5120]).
        size mismatch for up_blocks.1.attentions.1.transformer_blocks.0.ff.net.2.bias: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
        size mismatch for up_blocks.1.attentions.1.transformer_blocks.0.attn2.to_q.weight: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([1280, 1280]).
        size mismatch for up_blocks.1.attentions.1.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([640, 2048]) from checkpoint, the shape in current model is torch.Size([1280, 768]).
        size mismatch for up_blocks.1.attentions.1.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([640, 2048]) from checkpoint, the shape in current model is torch.Size([1280, 768]).
        size mismatch for up_blocks.1.attentions.1.transformer_blocks.0.attn2.to_out.0.weight: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([1280, 1280]).
        size mismatch for up_blocks.1.attentions.1.transformer_blocks.0.attn2.to_out.0.bias: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
        size mismatch for up_blocks.1.attentions.1.transformer_blocks.0.norm1.weight: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
        size mismatch for up_bloc
weight: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([1280, 1280]).
        size mismatch for up_blocks.1.attentions.2.transformer_blocks.0.attn1.to_v.weight: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([1280, 1280]).
        size mismatch for up_blocks.1.attentions.2.transformer_blocks.0.attn1.to_out.0.weight: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([1280, 1280]).
        size mismatch for up_blocks.1.attentions.2.transformer_blocks.0.attn1.to_out.0.bias: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
        size mismatch for up_blocks.1.attentions.2.transformer_blocks.0.ff.net.0.proj.weight: copying a param with shape torch.Size([5120, 640]) from checkpoint, the shape in current model is torch.Size([10240, 1280]).
        size mismatch for up_blocks.1.attentions.2.transformer_blocks.0.ff.net.0.proj.bias: copying a param with shape torch.Size([5120]) from checkpoint, the shape in current model is torch.Size([10240]).
        size mismatch for up_blocks.1.attentions.2.transformer_blocks.0.ff.net.2.weight: copying a param with shape torch.Size([640, 2560]) from checkpoint, the shape in current model is torch.Size([1280, 5120]).
        size mismatch for up_blocks.1.attentions.2.transformer_blocks.0.ff.net.2.bias: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
        size mismatch for up_blocks.1.attentions.2.transformer_blocks.0.attn2.to_q.weight: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([1280, 1280]).
        size mismatch for up_blocks.1.attentions.2.trans
ape torch.Size([1920]) from checkpoint, the shape in current model is torch.Size([2560]).
        size mismatch for up_blocks.1.resnets.0.conv1.weight: copying a param with shape torch.Size([640, 1920, 3, 3]) from checkpoint, the shape in current model is torch.Size([1280, 2560, 3, 3]).
        size mismatch for up_blocks.1.resnets.0.conv1.bias: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
        size mismatch for up_blocks.1.resnets.0.time_emb_proj.weight: copying a param with shape torch.Size([640, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1280]).
        size mismatch for up_blocks.1.resnets.0.time_emb_proj.bias: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
        size mismatch for up_blocks.1.resnets.0.norm2.weight: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
        size mismatch for up_blocks.1.resnets.0.norm2.bias: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
        size mismatch for up_blocks.1.resnets.0.conv2.weight: copying a param with shape torch.Size([640, 640, 3, 3]) from checkpoint, the shape in current model is torch.Size([1280, 1280, 3, 3]).
        size mismatch for up_blocks.1.resnets.0.conv2.bias: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
        size mismatch for up_blocks.1.resnets.0.conv_shortcut.weight
1920]).
        size mismatch for up_blocks.1.resnets.2.norm1.bias: copying a param with shape torch.Size([960]) from checkpoint, the shape in current model is torch.Size([1920]).
        size mismatch for up_blocks.1.resnets.2.conv1.weight: copying a param with shape torch.Size([640, 960, 3, 3]) from checkpoint, the shape in current model is torch.Size([1280, 1920, 3, 3]).
        size mismatch for up_blocks.1.resnets.2.conv1.bias: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
        size mismatch for up_blocks.1.resnets.2.time_emb_proj.weight: copying a param with shape torch.Size([640, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1280]).
        size mismatch for up_blocks.1.resnets.2.time_emb_proj.bias: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
        size mismatch for up_blocks.1.resnets.2.norm2.weight: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
        size mismatch for up_blocks.1.resnets.2.norm2.bias: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
        size mismatch for up_blocks.1.resnets.2.conv2.weight: copying a param with shape torch.Size([640, 640, 3, 3]) from checkpoint, the shape in current model is torch.Size([1280, 1280, 3, 3]).
        size mismatch for up_blocks.1.resnets.2.conv2.bias: copying a param with shape tor
0]).
        size mismatch for up_blocks.2.resnets.0.conv_shortcut.weight: copying a param with shape torch.Size([320, 960, 1, 1]) from checkpoint, the shape in current model is torch.Size([640, 1920, 1, 1]).
        size mismatch for up_blocks.2.resnets.0.conv_shortcut.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([640]).
        size mismatch for up_blocks.2.resnets.1.norm1.weight: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
        size mismatch for up_blocks.2.resnets.1.norm1.bias: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
        size mismatch for up_blocks.2.resnets.1.conv1.weight: copying a param with shape torch.Size([320, 6        size mismatch for up_blocks.2.resnets.2.conv1.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([640]).
        size mismatch for up_blocks.2.resnets.2.time_emb_proj.weight: copying a param with shape torch.Size([320, 1280]) from checkpoint, the shape in current model is torch.Size([640, 1280]).
        size mismatch for up_blocks.2.resnets.2.time_emb_proj.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([640]).
        size mismatch for up_blocks.2.resnets.2.norm2.weight: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([640]).
        size mismatch for up_blocks.2.resnets.2.norm2.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([640]).
        size mismatch for up_blocks.2.resnets.2.conv2.weight: copying a param with shape torch.Size([320, 320, 3, 3]) from checkpoint, the shape in current model is torch.Size([640, 640, 3, 3]).
        size mismatch for up_blocks.2.resnets.2.conv2.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([640]).
        size mismatch for up_blocks.2.resnets.2.conv_shortcut.weight: copying a param with shape torch.Size([320, 640, 1, 1]) from checkpoint, the shape in current model is torch.Size([640, 960, 1, 1]).
        size mismatch for up_blocks.2.resnets.2.conv_shortcut.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([640]).
        size mismatch for mid_block.attentions.0.proj_in.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1280, 1, 1]).
        size mismatch for mid_block.attentions.0.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([1280, 2048]) from checkpoint, the shape in current model is torch.Size([1280, 768]).
        size mismatch for mid_block.attentions.0.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([1280, 2048]) from checkpoint, the shape in current model is torch.Size([1280, 768]).
        size mismatch for mid_block.attentions.0.proj_out.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1280, 1, 1]).

**Comment by nanaj96** [comment]
> You forgot --is_sdxl


you mean like this

 python3 tools/extract_locon.py  --is_sdxl --safetensors --device=cuda --mode="fixed" --linear_dim=32 --conv_dim=32 /content/drive/MyDrive/ComfyUI/models/checkpoints/sd_xl_base_1.0.safetensors /content/drive/MyDrive/serena_sdxl/model/serena_sitter_dream_sdxl-000006.safetensors /content/drive/MyDrive/Lora/serena_sitter_lycoris.safetensors

**Comment by KohakuBlueleaf** [comment]
You are not in the last commit of fdv branch

**Comment by nanaj96** [comment]
> You are not in the last commit of fdv branch

![image](https://github.com/KohakuBlueleaf/LyCORIS/assets/120275578/25792e40-a51f-4b9e-8e50-d208bbf16406)
 but image use dev branch

**Comment by KohakuBlueleaf** [comment]
?
Can you run
git status
？

**Comment by nanaj96** [comment]
> ? Can you run git status ？

when i added git checkout dev this is work but now i getting this error what is the map_location

python3 tools/extract_locon.py  --is_sdxl --safetensors --device=cuda --mode="fixed" --linear_dim=32 --conv_dim=32 /content/drive/MyDrive/ComfyUI/models/checkpoints/sd_xl_base_1.0.safetensors /content/drive/MyDrive/serena_sdxl/model/serena_sitter_dream_sdxl-000006.safetensors /content/drive/MyDrive/Lora/serena_sitter_lycoris.safetensors
Traceback (most recent call last):
  File "/content/LyCORIS/tools/extract_locon.py", line 154, in <module>
    main()
  File "/content/LyCORIS/tools/extract_locon.py", line 103, in main
    base = load_models_from_sdxl_checkpoint(None, args.base_model)
TypeError: load_models_from_sdxl_checkpoint() missing 1 required positional argument: 'map_location'

**Comment by nanaj96** [comment]
> > > ? Can you run git status ？
> > 
> > 
> > when i added git checkout dev this is work but now i getting this error what is the map_location
> > python3 tools/extract_locon.py --is_sdxl --safetensors --device=cuda --mode="fixed" --linear_dim=32 --conv_dim=32 /content/drive/MyDrive/ComfyUI/models/checkpoints/sd_xl_base_1.0.safetensors /content/drive/MyDrive/serena_sdxl/model/serena_sitter_dream_sdxl-000006.safetensors /content/drive/MyDrive/Lora/serena_sitter_lycoris.safetensors Traceback (most recent call last): File "/content/LyCORIS/tools/extract_locon.py", line 154, in main() File "/content/LyCORIS/tools/extract_locon.py", line 103, in main base = load_models_from_sdxl_checkpoint(None, args.base_model) TypeError: load_models_from_sdxl_checkpoint() missing 1 required positional argument: 'map_location'
> 
> Ok now this is mu fault Fixed in merge just few hr ago Haven't fixed it in extract

can you please tell me when it can be fixed? I would be very grateful to you if you fix this quickly

**Comment by KohakuBlueleaf** [comment]
> > > > ? Can you run git status ？
> > > 
> > > 
> > > when i added git checkout dev this is work but now i getting this error what is the map_location
> > > python3 tools/extract_locon.py --is_sdxl --safetensors --device=cuda --mode="fixed" --linear_dim=32 --conv_dim=32 /content/drive/MyDrive/ComfyUI/models/checkpoints/sd_xl_base_1.0.safetensors /content/drive/MyDrive/serena_sdxl/model/serena_sitter_dream_sdxl-000006.safetensors /content/drive/MyDrive/Lora/serena_sitter_lycoris.safetensors Traceback (most recent call last): File "/content/LyCORIS/tools/extract_locon.py", line 154, in main() File "/content/LyCORIS/tools/extract_locon.py", line 103, in main base = load_models_from_sdxl_checkpoint(None, args.base_model) TypeError: load_models_from_sdxl_checkpoint() missing 1 required positional argument: 'map_location'
> > 
> > 
> > Ok now this is mu fault Fixed in merge just few hr ago Haven't fixed it in extract
> 
> can you please tell me when it can be fixed?

Now

**Comment by nanaj96** [comment]
> > > > > ? Can you run git status ？
> > > > 
> > > > 
> > > > when i added git checkout dev this is work but now i getting this error what is the map_location
> > > > python3 tools/extract_locon.py --is_sdxl --safetensors --device=cuda --mode="fixed" --linear_dim=32 --conv_dim=32 /content/drive/MyDrive/ComfyUI/models/checkpoints/sd_xl_base_1.0.safetensors /content/drive/MyDrive/serena_sdxl/model/serena_sitter_dream_sdxl-000006.safetensors /content/drive/MyDrive/Lora/serena_sitter_lycoris.safetensors Traceback (most recent call last): File "/content/LyCORIS/tools/extract_locon.py", line 154, in main() File "/content/LyCORIS/tools/extract_locon.py", line 103, in main base = load_models_from_sdxl_checkpoint(None, args.base_model) TypeError: load_models_from_sdxl_checkpoint() missing 1 required positional argument: 'map_location'
> > > 
> > > 
> > > Ok now this is mu fault Fixed in merge just few hr ago Haven't fixed it in extract
> > 
> > 
> > can you please tell me when it can be fixed?
> 
> Now

ok, thank you so much

**Comment by nanaj96** [comment]
do you know how to merge multiple lycoris models?

**Comment by KohakuBlueleaf** [comment]
> do you know how to merge multiple lycoris models?

If you have multiple lycoris model with different arch (or, different network_args/network_dim)
You need to merge them to a base model and then extract the final model into a locon with extract_locon.py

If you have multiple lycoris model with same arch. Just merge their state dict, you can find lot of examples from existing repo:

```py
for k, v in state_dict1.items():
  if k in state_dict2:
    state_dict_result[k] = v * a + state_dict2[k] * b
```

**Comment by nanaj96** [comment]
![image](https://github.com/KohakuBlueleaf/LyCORIS/assets/120275578/bfde7dea-c7e9-49dd-85be-4b6bd18de1d4)
now got this error lycoris merge are you sure you update merge.py file

**Comment by KohakuBlueleaf** [comment]
Add --is_sdzl

**Comment by nanaj96** [comment]
yeah sorry this my mistake this work now

**Comment by nanaj96** [comment]
any solution

**Comment by nanaj96** [comment]
hello any update about my issue

**Comment by nanaj96** [comment]
if i merge lycoris the file size is too large like 6.5 GB so i thought there was something wrong, and model results getting different

**Comment by nanaj96** [comment]
hey can you please resolve my issue when we extract the lycoris file, it is getting too big and it is working incorrectly, can you tell me if you can check this issue?
