### ISSUE TITLE
Using apply_max_norm_regularization with Diag-OFT crashes

### ISSUE THREAD

**Issue by rockerBOO** [KohakuBlueleaf/LyCORIS#131]
```
Traceback (most recent call last):
  File "/mnt/900/builds/sd-scripts/pti-te/train_network.py", line 1211, in <module>
    trainer.train(args)
  File "/mnt/900/builds/sd-scripts/pti-te/train_network.py", line 971, in train
    keys_scaled, mean_norm, maximum_norm = network.apply_max_norm_regularization(
  File "/mnt/900/builds/sd-scripts/.venv/lib/python3.10/site-packages/lycoris/kohya/__init__.py", line 595, in apply_max_norm_regularization
    scaled, norm = model.apply_max_norm(max_norm_value, device)
  File "/mnt/900/builds/sd-scripts/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/900/builds/sd-scripts/.venv/lib/python3.10/site-packages/lycoris/modules/diag_oft.py", line 127, in apply_max_norm
    orig_norm = self.oft_diag.to(device).norm()
  File "/mnt/900/builds/sd-scripts/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
  __
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DiagOFTModule' object has no attribute 'oft_diag'
```

Using scale_weight_norm=3 with Kohya-ss specifically. Removing that allows it to run. 

Related lines: 
https://github.com/KohakuBlueleaf/LyCORIS/blob/9366cdb3e2a1d649530ec1173701db33382b9845/lycoris/modules/diag_oft.py#L126C1-L128

Thank you :)

**Comment by KohakuBlueleaf** [comment]
Have pushed a fix to main
try to install from source to try this

Note: It is highly recommend to use constraing argument to control the OFT instead of apply max norm

**Comment by rockerBOO** [comment]
Cool it's working! I agree to not use it with constrain. Thank you!
