### ISSUE TITLE
AttributeError: 'DiagOFTModule' object has no attribute 'oft_diag'

### ISSUE THREAD

**Issue by bmaltais** [KohakuBlueleaf/LyCORIS#132]
Hello @KohakuBlueleaf, long time no talk. I have been trying to produce a Diag-OFT and I get this error when I run the code:

```
Traceback (most recent call last):
  File "D:\kohya_ss\train_network.py", line 1012, in <module>
    trainer.train(args)
  File "D:\kohya_ss\train_network.py", line 835, in train
    keys_scaled, mean_norm, maximum_norm = network.apply_max_norm_regularization(
  File "D:\kohya_ss\venv\lib\site-packages\lycoris\kohya\__init__.py", line 595, in apply_max_norm_regularization
    scaled, norm = model.apply_max_norm(max_norm_value, device)
  File "D:\kohya_ss\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\lycoris\modules\diag_oft.py", line 127, in apply_max_norm
    orig_norm = self.oft_diag.to(device).norm()
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DiagOFTModule' object has no attribute 'oft_diag'
```

I tought I was able to run it before but maybe not... Does this error ring a bell?

This is the sd-script command used to try to create the Diag-OFT:

```
accelerate launch --num_cpu_threads_per_process=2 "./train_network.py" --enable_bucket --min_bucket_reso=256 --max_bucket_reso=2048 --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5" --train_data_dir="F:\dataset\test\raccons\img" --resolution="512,512" --output_dir="E:/lora/sd1.5" --logging_dir="F:\dataset\test\raccons/log" --network_alpha="16" --training_comment="raccoons" --save_model_as=safetensors --network_module=lycoris.kohya --network_args      "preset=attn-mlp" "algo=diag-oft"  --network_dropout="0" --text_encoder_lr=0.0001 --unet_lr=0.0001 --network_dim=32 --output_name="raccoons-Diag-OFT-v1" --lr_scheduler_num_cycles="1" --scale_weight_norms="1" --no_half_vae --learning_rate="0.0001" --lr_scheduler="constant" --train_batch_size="1" --max_train_steps="113"        --mixed_precision="bf16" --save_precision="fp16" --seed="1234" --caption_extension=".txt" --cache_latents --cache_latents_to_disk --optimizer_type="AdamW" --optimizer_args   "weight_decay=0.1" "betas=0.9,0.99" --max_data_loader_n_workers="1" --clip_skip=2 --caption_dropout_rate="0.05" --bucket_reso_steps=1 --min_snr_gamma=5 --xformers --bucket_no_upscale --multires_noise_iterations="10" --multires_noise_discount="0.3"
```

**Comment by KohakuBlueleaf** [comment]
Plz check the closed issue.
This will be fixed in 2.0.1 which will be published later.
