### ISSUE TITLE
not enough values to unpack (expected 3, got 2) When extract

### ISSUE THREAD

**Issue by suede299** [KohakuBlueleaf/LyCORIS#144]
"tools\lycoris_locon_extract.py" --is_sdxl --device cpu --mode fixed --safetensors --linear_dim 48 --conv_dim 32 --use_sparse_bias --sparsity 0.99 --disable_cp

Traceback (most recent call last):
  File "D:\suede\Desktop\kohya_ss_GUI\kohya_ss\tools\lycoris_locon_extract.py", line 190, in <module>
    main()
  File "D:\suede\Desktop\kohya_ss_GUI\kohya_ss\tools\lycoris_locon_extract.py", line 169, in main
    state_dict = extract_diff(
                 ^^^^^^^^^^^^^
  File "D:\suede\Desktop\kohya_ss_GUI\kohya_ss\venv\Lib\site-packages\lycoris\utils\__init__.py", line 376, in extract_diff
    for idx, te1, te2 in enumerate(zip(base_tes, db_tes)):
        ^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by KohakuBlueleaf** [comment]
Already fixed in dev branch
