### ISSUE TITLE
[dev] saving weights positional argument error with koyha

### ISSUE THREAD

**Issue by rockerBOO** [KohakuBlueleaf/LyCORIS#184]
dev commit 7880753fb7f624e0d03a349db3ecf66b92a15c3e https://github.com/kohya-ss/sd-scripts/commit/e5bab69e3a8f3dc4afb1badba65b6c50ca2f36d8

```
Traceback (most recent call last):
  File "/mnt/900/builds/sd-scripts/train_network.py", line 1143, in <module>
    trainer.train(args)
  File "/mnt/900/builds/sd-scripts/train_network.py", line 995, in train
    save_model(ckpt_name, accelerator.unwrap_model(network), global_step, epoch + 1)
  File "/mnt/900/builds/sd-scripts/train_network.py", line 805, in save_model
    unwrapped_nw.save_weights(ckpt_file, save_dtype, metadata_to_save)
  File "/mnt/900/builds/sd-scripts/LyCORIS/lycoris/kohya.py", line 614, in save_weights
    model_hash, legacy_hash = precalculate_safetensors_hashes(
TypeError: precalculate_safetensors_hashes() takes 1 positional argument but 2 were given
```

Seems Kohya is trying to get a better hash by including the metadata? sd-scripts `train_util.py` `def precalucate_safetensors_hashes`

**Comment by KohakuBlueleaf** [comment]
Fixed in latest commit

**Comment by KohakuBlueleaf** [comment]
> Fixed in latest commit

My method doesn't want to include metadata though
