### ISSUE TITLE
[dev] precalculate_safetensors_hashes, ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by rockerBOO** [KohakuBlueleaf/LyCORIS#185]
```
Traceback (most recent call last):
  File "/mnt/900/builds/sd-scripts/train_network.py", line 1143, in <module>
    trainer.train(args)
  File "/mnt/900/builds/sd-scripts/train_network.py", line 995, in train
    save_model(ckpt_name, accelerator.unwrap_model(network), global_step, epoch + 1)
  File "/mnt/900/builds/sd-scripts/train_network.py", line 805, in save_model
    unwrapped_nw.save_weights(ckpt_file, save_dtype, metadata_to_save)
  File "/mnt/900/builds/sd-scripts/LyCORIS/lycoris/kohya.py", line 614, in save_weights
    model_hash, legacy_hash = precalculate_safetensors_hashes(
ValueError: too many values to unpack (expected 2)
```

Sorry, I tested again with the latest dev  9bbcd5a6fe46364052b755852d286aed9219b786

**Comment by Zanedname** [comment]
Hey buddy, did you solve the problem? I encountered the same issue today

**Comment by Zanedname** [comment]
I tried the development version update, but the issue still exists

**Comment by KohakuBlueleaf** [comment]
This issue have been fixed but not on pypi
You may need to install from source

**Comment by rockerBOO** [comment]
Can confirm this is now all working. Thank you @KohakuBlueleaf !
