### ISSUE TITLE
Running the latest extract_locon.py result in AttributeError: 'Namespace' object has no attribute 'disable_small_conv'

### ISSUE THREAD

**Issue by bmaltais** [KohakuBlueleaf/LyCORIS#20]
Here is the full command and resulting error:

```
python tools\extract_locon.py --mode quantile --safetensors --linear_quantile 0.75 --conv_quantile 0.75 --device cuda D:/models/v1-5-pruned.ckpt "C:\Users\berna\Downloads\deliberate_v2.safetensors" "D:/lora/sd1.5/deliberate_v2.safetensors"

Traceback (most recent call last):
  File "D:\kohya_ss\tools\lycoris_locon_extract.py", line 129, in <module>
    main()
  File "D:\kohya_ss\tools\lycoris_locon_extract.py", line 119, in main
    not args.disable_small_conv
AttributeError: 'Namespace' object has no attribute 'disable_small_conv'
```

**Comment by bmaltais** [comment]
Commenting out line 119 fixes the issue... Look like there might be a missing argument in the version of the code. But then I receive this one:

```
loading text encoder: <All keys matched successfully>
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 152/152 [00:05<00:00, 26.21it/s]
 10%|████████████████▋                                                                                                                                                          | 69/709 [00:00<00:06, 92.93it/s] 
Traceback (most recent call last):
  File "D:\kohya_ss\tools\lycoris_locon_extract.py", line 129, in <module>
    main()
  File "D:\kohya_ss\tools\lycoris_locon_extract.py", line 113, in main
    state_dict = extract_diff(
  File "D:\kohya_ss\venv\lib\site-packages\lycoris\utils.py", line 250, in extract_diff
    unet_loras = make_state_dict(
  File "D:\kohya_ss\venv\lib\site-packages\lycoris\utils.py", line 221, in make_state_dict
    diff = child_module.weight - torch.einsum(
  File "D:\kohya_ss\venv\lib\site-packages\torch\functional.py", line 360, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
RuntimeError: einsum(): operands do not broadcast with remapped shapes [original->remapped]: [203, 203, 3, 3]->[1, 1, 3, 3, 203, 203] [203, 320]->[1, 320, 1, 1, 1, 203] [320, 203]->[203, 1, 1, 1, 320, 1]  
```

**Comment by KohakuBlueleaf** [comment]
Fixed, please check it

**Comment by sashasubbbb** [comment]
```
Traceback (most recent call last):
  File "B:\AIimages\sd-scripts\sd-scripts\LyCORIS\tools\extract_locon.py", line 129, in <module>
    main()
  File "B:\AIimages\sd-scripts\sd-scripts\LyCORIS\tools\extract_locon.py", line 113, in main
    state_dict = extract_diff(
TypeError: extract_diff() takes from 2 to 8 positional arguments but 9 were given
```

**Comment by KohakuBlueleaf** [comment]
@sashasubbbb What is the commit id?

**Comment by sashasubbbb** [comment]
@KohakuBlueleaf commit 239992c80010fcae5bb5208a24447301e7f6f8b3
it seems that commenting out `not args.disable_cp` just like @bmaltais suggested fixed the problem, and i'm able to extract the locon.

**Comment by KohakuBlueleaf** [comment]
@sashasubbbb ???that is not normal
disable_cp is in the namespace

**Comment by bmaltais** [comment]
Good morning. Sorry to reply this late. Yesterday's commit solved the issue.
