### ISSUE TITLE
base_weights didn't available, it would crash when trying to use it

### ISSUE THREAD

**Issue by And233** [KohakuBlueleaf/LyCORIS#228]
both sd-script and lycoris have already been updated to the newest version

Traceback (most recent call last):
  File "/home/arraneye/lora-scripts/./scripts/stable/sdxl_train_network.py", line 185, in <module>
    trainer.train(args)
  File "/home/arraneye/lora-scripts/scripts/stable/train_network.py", line 262, in train
    module.merge_to(text_encoder, unet, weights_sd, weight_dtype, accelerator.device if args.lowram else "cpu")
  File "/home/arraneye/lora-scripts/venv/lib/python3.10/site-packages/lycoris/kohya.py", line 590, in merge_to
    super().merge_to(1)
  File "/home/arraneye/lora-scripts/venv/lib/python3.10/site-packages/lycoris/wrapper.py", line 569, in merge_to
    lora.merge_to(weight)
  File "/home/arraneye/lora-scripts/venv/lib/python3.10/site-packages/lycoris/modules/base.py", line 281, in merge_to
    weight, bias = self.get_merged_weight(
  File "/home/arraneye/lora-scripts/venv/lib/python3.10/site-packages/lycoris/modules/full.py", line 193, in get_merged_weight
    weight, bias = self.make_weight(multiplier, device)
  File "/home/arraneye/lora-scripts/venv/lib/python3.10/site-packages/lycoris/modules/full.py", line 160, in make_weight
    bias = self.org_bias + diff_b * drop
TypeError: can only concatenate list (not "Tensor") to list

**Comment by KohakuBlueleaf** [comment]
Fixed in 82df4aa. `org_bias` is cached as a one-element list (like `_org_weight`), so `self.org_bias + diff_b * drop` was list + Tensor - that whole fallback path in `FullModule.make_weight` was broken and is rebuilt from the cache now. Same commit also fixes algo=full raising AttributeError on the first forward after `apply_to()`, which you would have hit right after this one.
