### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by biasnhbi** [KohakuBlueleaf/LyCORIS#87]
I use sd-scripts to train loha,This error occurs when merging loha into SD1.5 using merge.py,
LyCORIS==1.8.0

```A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
Merging lora_te:   5%|████▉                                                                                        | 8/152 [00:03<01:06,  2.16it/s]
Traceback (most recent call last):
  File "g:\Software\LyCORIS\tools\merge.py", line 84, in <module>
    main()
  File "g:\Software\LyCORIS\tools\merge.py", line 68, in main
    merge(
  File "D:\ProgramData\Anaconda3\envs\kohya\lib\site-packages\lycoris\utils\__init__.py", line 494, in merge
    merge_state_dict(
  File "D:\ProgramData\Anaconda3\envs\kohya\lib\site-packages\lycoris\utils\__init__.py", line 471, in merge_state_dict
    result = rebuild_weight(*get_module(
  File "D:\ProgramData\Anaconda3\envs\kohya\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\kohya\lib\site-packages\lycoris\utils\__init__.py", line 399, in rebuild_weight
    merged = orig_weight + rebuild * scale
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by KohakuBlueleaf** [comment]
will check that

**Comment by KohakuBlueleaf** [comment]
you may need to use cpu to merge the weight for now

**Comment by biasnhbi** [comment]
> 您现在可能需要使用 CPU 来合并权重

Yes, I used cpu and cuda to combine weights, but it also failed

**Comment by biasnhbi** [comment]
> you may need to use cpu to merge the weight for now

Yes, I used cpu and cuda to combine weights, but it also failed

**Comment by KohakuBlueleaf** [comment]
？
So you use --device cpu
And --device cuda
And both failed?

**Comment by biasnhbi** [comment]
> ？ So you use --device cpu And --device cuda And both failed?

yes

**Comment by KohakuBlueleaf** [comment]
@biasnhbi I pushed a commit on dev branch for this problem
can you try to use that?
use
`git switch dev` and `git pull` to use that update

**Comment by biasnhbi** [comment]
> @biasnhbi I pushed a commit on dev branch for this problem can you try to use that? use and to use that update`git switch dev``git pull`

I used the changed code in LyCORIS==1.8.0，and now the merge is successful
